/**
 * renderMarkdown.ts – Render a Roadmap as a human-readable Markdown document.
 */

import type { Roadmap, PlanStep, VerificationItem, RiskItem, QuestionRef } from "../contracts/phase3";

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function h(level: number, text: string): string {
  return `${"#".repeat(level)} ${text}`;
}

function bullet(text: string, indent = 0): string {
  return `${" ".repeat(indent * 2)}- ${text}`;
}

function checkbox(text: string, checked = false): string {
  return `- [${checked ? "x" : " "}] ${text}`;
}

function codeBlock(lang: string, text: string): string {
  return `\`\`\`${lang}\n${text}\n\`\`\``;
}

function sep(): string {
  return "\n---\n";
}

function badge(label: string, value: string): string {
  return `**${label}:** ${value}`;
}

// ---------------------------------------------------------------------------
// Renderers
// ---------------------------------------------------------------------------

function renderStep(step: PlanStep, idx: number): string {
  const lines: string[] = [];

  lines.push(h(3, `Step ${idx + 1}: ${step.title}`));
  lines.push("");
  lines.push(
    `${badge("ID", step.id)} | ${badge("Area", step.area)} | ${badge("Kind", step.kind)}`
  );
  lines.push("");
  lines.push(step.description);
  lines.push("");

  if (step.files.modify.length > 0) {
    lines.push(h(4, "Files to Modify"));
    step.files.modify.forEach((f) => lines.push(bullet(`\`${f}\``)));
    lines.push("");
  }

  if (step.files.create.length > 0) {
    lines.push(h(4, "Files to Create"));
    step.files.create.forEach((f) => lines.push(bullet(`\`${f}\``)));
    lines.push("");
  }

  if (step.files.touch.length > 0) {
    lines.push(h(4, "Blast Radius (Touch / Be Aware)"));
    step.files.touch.slice(0, 8).forEach((f) => lines.push(bullet(`\`${f}\``)));
    lines.push("");
  }

  if (step.dependsOnStepIds.length > 0) {
    lines.push(
      `**Depends on:** ${step.dependsOnStepIds.map((id) => `\`${id}\``).join(", ")}`
    );
    lines.push("");
  }

  lines.push(h(4, "Rationale"));
  step.rationale.forEach((r) => lines.push(bullet(r)));
  lines.push("");

  lines.push(h(4, "Implementation Checklist"));
  step.implementationChecklist.forEach((item) =>
    lines.push(checkbox(item))
  );
  lines.push("");

  lines.push(h(4, "Done When"));
  step.doneWhen.forEach((d) => lines.push(bullet(d)));
  lines.push("");

  return lines.join("\n");
}

function renderVerification(items: VerificationItem[]): string {
  const lines: string[] = [h(2, "Verification Suite"), ""];
  for (const item of items) {
    lines.push(h(3, item.type.replace(/_/g, " ").toUpperCase()));
    item.instructions.forEach((i) => lines.push(checkbox(i)));
    lines.push("");
  }
  return lines.join("\n");
}

function renderRisks(risks: RiskItem[]): string {
  const lines: string[] = [h(2, "Risks"), ""];
  for (const risk of risks) {
    const severityIcon =
      risk.severity === "high" ? "🔴" : risk.severity === "medium" ? "🟡" : "🟢";
    lines.push(h(3, `${severityIcon} ${risk.severity.toUpperCase()}: ${risk.risk}`));
    lines.push("");
    lines.push(h(4, "Mitigation"));
    risk.mitigation.forEach((m) => lines.push(bullet(m)));
    lines.push("");
  }
  return lines.join("\n");
}

function renderQuestions(questions: QuestionRef[]): string {
  if (questions.length === 0) return "";
  const lines: string[] = [h(2, "Open Questions (Blocking)"), ""];
  for (const q of questions) {
    lines.push(
      `**[${q.id}]** ${q.blocking ? "🚧 BLOCKING" : ""} ${q.question}`
    );
    q.whyThisMatters.forEach((w) => lines.push(bullet(w, 1)));
    lines.push("");
  }
  return lines.join("\n");
}

// ---------------------------------------------------------------------------
// Main render function
// ---------------------------------------------------------------------------

export function renderRoadmapMarkdown(roadmap: Roadmap): string {
  const lines: string[] = [];

  // ── Header ─────────────────────────────────────────────────────────────
  lines.push(h(1, "Technical Roadmap"));
  lines.push("");
  lines.push(
    `> Generated by Phase-3 Grounded Architect on ${roadmap.generatedAt}`
  );
  lines.push("");
  lines.push(
    `**PRD Hash:** \`${roadmap.prd.hash}\`` +
      (roadmap.prd.source ? `  **Source:** ${roadmap.prd.source}` : "")
  );
  lines.push("");
  lines.push(sep());

  // ── Summary ────────────────────────────────────────────────────────────
  lines.push(h(2, "Summary"));
  lines.push("");
  lines.push(
    `| Metric | Value |
|--------|-------|
| Total Steps | ${roadmap.plan.length} |
| Files to Modify | ${roadmap.artifacts.filesToModify.length} |
| Files to Create | ${roadmap.artifacts.filesToCreate.length} |
| Acceptance Criteria | ${roadmap.acceptanceCriteria.length} |
| Risks | ${roadmap.risks.length} |
| Open Questions | ${roadmap.openQuestions.length} |`
  );
  lines.push("");
  lines.push(sep());

  // ── Acceptance Criteria ────────────────────────────────────────────────
  lines.push(h(2, "Acceptance Criteria"));
  lines.push("");
  roadmap.acceptanceCriteria.forEach((ac) => lines.push(checkbox(ac)));
  lines.push("");
  lines.push(sep());

  // ── Plan Steps ─────────────────────────────────────────────────────────
  lines.push(h(2, "Implementation Plan"));
  lines.push("");

  // Table of contents
  roadmap.plan.forEach((step, idx) => {
    lines.push(
      bullet(
        `**Step ${idx + 1}:** ${step.title} *(${step.area} / ${step.kind})*`
      )
    );
  });
  lines.push("");
  lines.push(sep());

  roadmap.plan.forEach((step, idx) => {
    lines.push(renderStep(step, idx));
    lines.push(sep());
  });

  // ── Artifacts ──────────────────────────────────────────────────────────
  lines.push(h(2, "Artifact Inventory"));
  lines.push("");

  if (roadmap.artifacts.filesToCreate.length > 0) {
    lines.push(h(3, "Files to Create"));
    roadmap.artifacts.filesToCreate.forEach((f) => lines.push(bullet(`\`${f}\``)));
    lines.push("");
  }

  if (roadmap.artifacts.filesToModify.length > 0) {
    lines.push(h(3, "Files to Modify"));
    roadmap.artifacts.filesToModify.forEach((f) => lines.push(bullet(`\`${f}\``)));
    lines.push("");
  }

  if (roadmap.artifacts.dependencies.length > 0) {
    lines.push(h(3, "Dependencies"));
    for (const dep of roadmap.artifacts.dependencies) {
      lines.push(
        bullet(
          `**${dep.kind}** \`${dep.target ?? dep.name ?? "?"}\` – status: ${dep.status}`
        )
      );
      dep.why.forEach((w) => lines.push(bullet(w, 1)));
    }
    lines.push("");
  }

  lines.push(sep());

  // ── Verification ───────────────────────────────────────────────────────
  lines.push(renderVerification(roadmap.verification));
  lines.push(sep());

  // ── Risks ──────────────────────────────────────────────────────────────
  lines.push(renderRisks(roadmap.risks));
  lines.push(sep());

  // ── Open Questions ─────────────────────────────────────────────────────
  const qSection = renderQuestions(roadmap.openQuestions);
  if (qSection) {
    lines.push(qSection);
    lines.push(sep());
  }

  // ── Notes ──────────────────────────────────────────────────────────────
  if (roadmap.notes.length > 0) {
    lines.push(h(2, "Notes"));
    lines.push("");
    roadmap.notes.forEach((n) => lines.push(bullet(n)));
    lines.push("");
  }

  return lines.join("\n");
}

// suppress unused imports
void codeBlock;
void badge;
